//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenboGeneral
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmpWebServiceSoap")]
    public interface SmpWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 content 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        SendSmsResponse SendSms(SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSmsResponse> SendSmsAsync(SendSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 businessId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuerySms", ReplyAction="*")]
        QuerySmsResponse QuerySms(QuerySmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuerySms", ReplyAction="*")]
        System.Threading.Tasks.Task<QuerySmsResponse> QuerySmsAsync(QuerySmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addresseeTel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime sendTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string appCode;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string content, string addresseeTel, System.DateTime sendTime, string userAccount, string password, string appCode) {
            this.content = content;
            this.addresseeTel = addresseeTel;
            this.sendTime = sendTime;
            this.userAccount = userAccount;
            this.password = password;
            this.appCode = appCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuerySmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuerySms", Namespace="http://tempuri.org/", Order=0)]
        public QuerySmsRequestBody Body;
        
        public QuerySmsRequest() {
        }
        
        public QuerySmsRequest(QuerySmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuerySmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string businessId;
        
        public QuerySmsRequestBody() {
        }
        
        public QuerySmsRequestBody(string businessId) {
            this.businessId = businessId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuerySmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuerySmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuerySmsResponseBody Body;
        
        public QuerySmsResponse() {
        }
        
        public QuerySmsResponse(QuerySmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuerySmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QuerySmsResult;
        
        public QuerySmsResponseBody() {
        }
        
        public QuerySmsResponseBody(string QuerySmsResult) {
            this.QuerySmsResult = QuerySmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmpWebServiceSoapChannel : SmpWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmpWebServiceSoapClient : System.ServiceModel.ClientBase<SmpWebServiceSoap>, SmpWebServiceSoap {
        
        public SmpWebServiceSoapClient() {
        }
        
        public SmpWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSmsResponse SmpWebServiceSoap.SendSms(SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string content, string addresseeTel, System.DateTime sendTime, string userAccount, string password, string appCode) {
            SendSmsRequest inValue = new SendSmsRequest();
            inValue.Body = new SendSmsRequestBody();
            inValue.Body.content = content;
            inValue.Body.addresseeTel = addresseeTel;
            inValue.Body.sendTime = sendTime;
            inValue.Body.userAccount = userAccount;
            inValue.Body.password = password;
            inValue.Body.appCode = appCode;
            SendSmsResponse retVal = ((SmpWebServiceSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSmsResponse> SmpWebServiceSoap.SendSmsAsync(SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSmsResponse> SendSmsAsync(string content, string addresseeTel, System.DateTime sendTime, string userAccount, string password, string appCode) {
            SendSmsRequest inValue = new SendSmsRequest();
            inValue.Body = new SendSmsRequestBody();
            inValue.Body.content = content;
            inValue.Body.addresseeTel = addresseeTel;
            inValue.Body.sendTime = sendTime;
            inValue.Body.userAccount = userAccount;
            inValue.Body.password = password;
            inValue.Body.appCode = appCode;
            return ((SmpWebServiceSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuerySmsResponse SmpWebServiceSoap.QuerySms(QuerySmsRequest request) {
            return base.Channel.QuerySms(request);
        }
        
        public string QuerySms(string businessId) {
            QuerySmsRequest inValue = new QuerySmsRequest();
            inValue.Body = new QuerySmsRequestBody();
            inValue.Body.businessId = businessId;
            QuerySmsResponse retVal = ((SmpWebServiceSoap)(this)).QuerySms(inValue);
            return retVal.Body.QuerySmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuerySmsResponse> SmpWebServiceSoap.QuerySmsAsync(QuerySmsRequest request) {
            return base.Channel.QuerySmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuerySmsResponse> QuerySmsAsync(string businessId) {
            QuerySmsRequest inValue = new QuerySmsRequest();
            inValue.Body = new QuerySmsRequestBody();
            inValue.Body.businessId = businessId;
            return ((SmpWebServiceSoap)(this)).QuerySmsAsync(inValue);
        }
    }
}
